### ISSUE TITLE
在 CollectionUtils 中增加 groupList 方法

### ISSUE THREAD

**Issue by toulezu** [dzoverflow/xutils#6]
/**
	 * 这里的 targetList 相当于数据库中的一张表, 通过 key 将这张表分隔成若干张子表
	 * 
	 * @param key
	 *            表中的某个字段
	 * @param targetList
	 *            数据表
	 * @return Map<String, List<Map<String, Object>>> 以 key 的值为键, 以
	 *         List<Map<String, Object>> 为值
	 */
	public static Map<String, List<Map<String, Object>>> groupList(final String key, List<Map<String, Object>> targetList) {
		// 首先根据 key 将目标集合排序
		Collections.sort(targetList, new Comparator<Map<String, Object>>() {
			@Override
			public int compare(Map<String, Object> o1, Map<String, Object> o2) {
				String keyValue1 = StringUtils.getStr(o1.get(key));
				String keyValue2 = StringUtils.getStr(o2.get(key));
				return keyValue1.compareTo(keyValue2);
			}
		});

		Map<String, List<Map<String, Object>>> groupMap = new LinkedHashMap<>();
		String tempKeyValue = "";
		List<Map<String, Object>> tempDataList = new ArrayList<>();
		for (int i = 0, c = CollectionUtils.getSize(targetList); i < c; i++) {
			Map<String, Object> data = targetList.get(i);
			String keyValue = StringUtils.getStr(data.get(key));
			// 遍历开始, 初始化临时key的值
			if (i == 0) {
				tempKeyValue = keyValue;
			}

			// 关键Key的值不同的时候开始分组
			if (!tempKeyValue.equals(keyValue)) {
				// 将分组数据存入返回的Map中
				groupMap.put(tempKeyValue, tempDataList);

				// 初始化临时Map
				tempDataList = new ArrayList<>();
				tempDataList.add(data);

				// 初始化临时key的值
				tempKeyValue = keyValue;
			} else {
				tempDataList.add(data);
			}

			// 遍历结束, 将最后一个分组存入返回的Map中
			if (i == c - 1) {
				groupMap.put(tempKeyValue, tempDataList);
			}
		}

		return groupMap;
	}

// -------------------------------------------------------------

@Test
	public void groupList() {
		List<Map<String, Object>> targetList = new ArrayList<>();
		Map<String, Object> data = new HashMap<>();
		data.put("class", "一班");
		data.put("name", "张三");
		data.put("age", "20");
		data.put("sex", "男");
		targetList.add(data);
		
		data = new HashMap<>();
		data.put("class", "一班");
		data.put("name", "李四");
		data.put("age", "21");
		data.put("sex", "女");
		targetList.add(data);
		
		data = new HashMap<>();
		data.put("class", "一班");
		data.put("name", "王五");
		data.put("age", "23");
		data.put("sex", "男");
		targetList.add(data);
		
		data = new HashMap<>();
		data.put("class", "二班");
		data.put("name", "张三");
		data.put("age", "20");
		data.put("sex", "男");
		targetList.add(data);
		
		data = new HashMap<>();
		data.put("class", "二班");
		data.put("name", "李四");
		data.put("age", "21");
		data.put("sex", "女");
		targetList.add(data);
		
		data = new HashMap<>();
		data.put("class", "二班");
		data.put("name", "王五");
		data.put("age", "23");
		data.put("sex", "男");
		targetList.add(data);
		
		data = new HashMap<>();
		data.put("class", "二班");
		data.put("name", "mandy");
		data.put("age", "23");
		data.put("sex", "女");
		targetList.add(data);
		
		Map<String, List<Map<String, Object>>> groupMap = groupList("class", targetList);
		List<Map<String, Object>> dataList = groupMap.get("一班");
		assertTrue(dataList.size() == 3);
		for (Map<String, Object> map : dataList) {
			assertTrue(map.get("class").toString().equals("一班"));
		}
		
		dataList = groupMap.get("二班");
		assertTrue(dataList.size() == 4);
		for (Map<String, Object> map : dataList) {
			assertTrue(map.get("class").toString().equals("二班"));
		}
		
	}

**Comment by dzoverflow** [comment]
ok
